name: Run tests

on:
  push:
    branches: [ main, work ]
  pull_request:

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo test
        run: cargo test --manifest-path rust/Cargo.toml -- --nocapture

